<?xml version="1.0"?>
<robot name="mamba" xmlns:xacro="http://ros.org/wiki/xacro">

	<!-- Include RealSense Camera -->
    <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro"/>

    <!-- Create camera link and joint -->
    <xacro:sensor_d435 parent="base_link">
    	<origin xyz="0 0 0.15" rpy="0 0 0"/>
    </xacro:sensor_d435>

	<!-- Robot parameters -->
	<xacro:property name="wheel_radius" value="0.033"/>
	<xacro:property name="wheel_distance" value="0.12"/>

	<material name="DarkGray">
          <color rgba="0.2 0.2 0.2 1.0"/>
    </material>
	
	<!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin, navigation stack depends on this frame -->
	<link name="base_footprint">
	 	<collision>
	      		<origin xyz="0 0 0" rpy="0 0 0" />
	      		<geometry>
	        		<cylinder length="0" radius="0.16495"/>
	     	 	</geometry>
	    	</collision>
	</link>
	
	<!-- base link, basically the body of the Roomba -->
	<link name="base_link">
		<inertial>
	     		<mass value="2" />
	      		<origin xyz="0 0 0.0" />
	      		<inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.5" />
	 	</inertial>
	
	    	<visual>
	      		<origin xyz=" 0 0 0.0308" rpy="0 0 1.5708" />
	      		<geometry>
	        		<mesh filename="package://mamba_description/meshes/black_roomba.dae"/>
	      		</geometry>
	    	</visual>
	
	    	<collision>
	      		<origin xyz="0.0 0.0 0.0358" rpy="0 0 0" />
	      		<geometry>
	        		<cylinder length="0.0711632" radius="0.16495"/>
	     	 	</geometry>
	    	</collision>
	</link>

	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0.017" rpy="0 0 0" />        
		<parent link="base_footprint"/>
	 	<child link="base_link" />
	</joint>
	

	<!-- cliff sensors -->
	<link name="left_cliff_sensor_link">
		<inertial>
			<mass value="0.01" />
	  		<origin xyz="0 0 0"/>
	     		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	   	</inertial>
	</link>
	
	<link name="right_cliff_sensor_link">
	 	<inertial>
	     		<mass value="0.01" />
	    		<origin xyz="0 0 0"/>
	    		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	    	</inertial>
	</link>
	
	<link name="front_left_cliff_sensor_link">
	 	<inertial>
	     		<mass value="0.01" />
	      		<origin xyz="0 0 0"/>
	      		<inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
	    	</inertial>
	</link>
	
	 <link name="front_right_cliff_sensor_link">
		<inertial>
	     		<mass value="0.01" />
	      		<origin xyz="0 0 0"/>
	      		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	    	</inertial>
	</link>
	
	<joint name="left_sensor_joint" type="fixed">
	  	<origin xyz="0.07 0.14 0.01" rpy="0 1.57079 0" />        
	    	<parent link="base_link"/>
	    	<child link="left_cliff_sensor_link" />
	</joint>
	
	<joint name="right_cliff_sensor_joint" type="fixed">
		<origin xyz="0.07 -0.14 0.01" rpy="0 1.57079 0" />        
		<parent link="base_link"/>
	 	<child link="right_cliff_sensor_link" />
	</joint>
	
	<joint name="front_left_cliff_sensor_joint" type="fixed">
	    	<origin xyz="0.15 0.04 0.01" rpy="0 1.57079 0" />        
	    	<parent link="base_link"/>
	    	<child link="front_left_cliff_sensor_link" />
	</joint>
	
	<joint name="front_right_cliff_sensor_joint" type="fixed">
	    	<origin xyz="0.15 -0.04 0.01" rpy="0 1.57079 0" />        
	    	<parent link="base_link"/>
	    	<child link="front_right_cliff_sensor_link" />
	</joint>


	<!-- bumpers -->
	<link name="left_bumper_link">
		<inertial>
	   	<mass value="0.01" />
	      	<origin xyz="0 0 0"/>
	      		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	    	</inertial>
	</link>
	
	<link name="right_bumper_link">
		<inertial>
	   	<mass value="0.01" />
	      	<origin xyz="0 0 0"/>
	      		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	    	</inertial>
	</link>

	<joint name="left_bumper_joint" type="fixed">
	  	<origin xyz="0.115 -0.115 0.042" rpy="0 0 -0.75" />        
	    	<parent link="base_link"/>
	    	<child link="left_bumper_link" />
	</joint>

	<joint name="right_bumper_joint" type="fixed">
	  	<origin xyz="0.115 0.115 0.042" rpy="0 0 0.75" />        
	    	<parent link="base_link"/>
	    	<child link="right_bumper_link" />
	</joint>


	<!-- wheels and caster wheel -->
	 <link name="left_wheel_link">
		<inertial>
	      		<origin xyz="0 0 0"/>
	      		<mass value="0.01" />
	      		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	    	</inertial>
	
	    	<visual>
	      		<origin xyz="0 0 0" rpy="0 0 0" />
	      		<geometry>
	        		<cylinder radius="${wheel_radius}" length = "0.023"/>
	      		</geometry>
			<material name="DarkGray" />
	    	</visual>
	
	    	<collision>
	      		<origin xyz="0 0 0" rpy="0 0 0" />
	      		<geometry>
	        		<sphere radius="${wheel_radius}"/>
	      		</geometry>
	    	</collision>
	</link>
	
	<joint name="left_wheel_joint" type="continuous">
	 	<origin xyz="0 ${wheel_distance} 0.015" rpy="${-1*pi/2} 0 0"/>
	    	<parent link="base_link"/>
	    	<child link="left_wheel_link"/>
	    	<axis xyz="0 0 1"/>
	  </joint>
	
	<link name="right_wheel_link">
	    	<inertial>
	      		<origin xyz="0 0 0"/>
	      		<mass value="0.01" />
	      		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	    	</inertial>
	
	    	<visual>
	      		<origin xyz="0 0 0" rpy="0 0 0" />
	      		<geometry>
	        		<cylinder radius="${wheel_radius}" length = "0.023"/>
	      		</geometry>
			<material name="DarkGray" />
	    	</visual>
	
	  	<collision>
	      		<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
	      		<geometry>
	        		<sphere radius="${wheel_radius}"/>
	      		</geometry>
	    	</collision>
	</link>
	
	<joint name="right_wheel_joint" type="continuous">
	  	<origin xyz="0 ${-1*wheel_distance} 0.015" rpy="${-1*pi/2} 0 0"/>
	    	<parent link="base_link"/>
	    	<child link="right_wheel_link"/>
	    	<axis xyz="0 0 1"/>
	</joint>
	
	<link name="caster_wheel_link">
		<inertial>
	      		<origin xyz="0 0 0" />
	      		<mass value="0.01" />
	      		<inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
	    	</inertial>
	
	    	<visual>
	      		<origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
	      		<geometry>
	        		<sphere radius="0.018" />
	      		</geometry>
			<material name="DarkGray" />
	    	</visual>
	
	    	<collision>
	      		<origin xyz="0 0 0" rpy="0 1.5707 1.5707" />
	      		<geometry>
	        		<sphere radius="0.018" />
	      		</geometry>
	    	</collision>
	</link>
	
	<joint name="caster_wheel_joint" type="fixed">
	 	<origin xyz="0.12 0 0.0" rpy="0 0 0"/>
	    	<parent link="base_link"/>
	    	<child link="caster_wheel_link"/>
	    	<axis xyz="0 1 0"/>
	</joint>

</robot>
